name: Feature Request
description: Propose a new feature, DSP character, or UI enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem or limitation is.
    validations:
      required: false
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the feature or improvement you would like to see added.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you have considered.
    validations:
      required: false
